repositories {
	mavenLocal()
	mavenCentral()
	maven {
		name "Modmaven"
		url "https://modmaven.dev"
		content {
			// GrandPower
			includeGroup "dev.technici4n"
			// Modern Industrialization
			includeGroup "aztech"
			// Tesseract
			includeGroup "net.swedz"
			// Almost Unified
			includeGroup "com.almostreliable.mods"
			// JEI - Required by Create for JEMI
			includeGroup "mezz.jei"
		}
	}
	maven {
		name = "Sleeping Town"
		url = "https://repo.sleeping.town/"
		content {
			// EMI
			includeGroup "dev.emi"
		}
	}
	maven {
		name = "Wisp Forest"
		url = "https://maven.wispforest.io/releases"
		// Accessories
	}
	maven {
		name = "Su5eD"
		url = "https://maven.su5ed.dev/releases"
		content {
			// Forgified Fabric API - Required by Accessories
			includeGroup "org.sinytra.forgified-fabric-api"
		}
	}
	maven {
		name = "Illusive Soulwork"
		url = "https://maven.theillusivec4.top/"
		content {
			// Curios
			includeGroup "top.theillusivec4.curios"
		}
	}
	maven {
		name "Sonatype"
		url = "https://central.sonatype.com/repository/maven-snapshots/"
		content {
			// GuideME
			includeGroup "org.appliedenergistics"
		}
	}
	maven {
		name "Create"
		url = "https://maven.createmod.net/"
		content {
			// Create
			includeGroup "com.simibubi.create"
			includeGroup "net.createmod.ponder"
			includeGroup "dev.engine-room.flywheel"
			includeGroup "dev.engine-room.vanillin"
		}
	}
	maven {
		url "https://maven.ithundxr.dev/snapshots"
		content {
			// Registrate - Required by Create
			includeGroup "com.tterrag.registrate"
		}
	}
}

dependencies {
	implementation ("aztech:Modern-Industrialization:${modern_industrialization_version}") {
		// TODO remove this when MI updates to 2.5.10
		exclude group: "com.simibubi.create"
	}

	implementation "dev.technici4n:GrandPower:${grandpower_version}"

	if (project.runtime_include_emi.toBoolean()) {
		localImplementation "dev.emi:emi-neoforge:${emi_version}"
	} else {
		compileOnly "dev.emi:emi-neoforge:${emi_version}"
	}

	implementation "net.swedz:tesseract-api-neoforge:${tesseract_version}"

	if (project.runtime_include_mi_tweaks.toBoolean()) {
		localImplementation "net.swedz:mi-tweaks:${mi_tweaks_version}"
	} else {
		compileOnly "net.swedz:mi-tweaks:${mi_tweaks_version}"
	}

	if (project.runtime_include_accessories.toBoolean()) {
		localImplementation "io.wispforest:accessories-neoforge:${accessories_version}"
	} else {
		compileOnly "io.wispforest:accessories-neoforge:${accessories_version}"
	}

	if (project.runtime_include_curios.toBoolean()) {
		localImplementation "top.theillusivec4.curios:curios-neoforge:${curios_version}"
	} else {
		compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
	}

	compileOnly "com.almostreliable.mods:almostunified-neoforge:${project.minecraft_version}-${project.au_version}:api"

	localImplementation "org.appliedenergistics:guideme:${guideme_version}"

	localRuntimeOnly ("com.simibubi.create:create-1.21.1:${project.create_version}") {
		exclude group: "cc.tweaked"
		exclude group: "top.theillusivec4.curios"
		exclude group: "info.journeymap"
		exclude group: "maven.modrinth", module: "journeymap"
		exclude group: "maven.modrinth", module: "farmers-delight"
		exclude group: "dev.architectury"
		exclude group: "dev.ftb.mods"
	}
}