publishing {
	repositories {
		mavenLocal()
	}
	
	publications {
		register("mavenJava", MavenPublication) {
			from components.java
			artifactId = project.artifact_name
			artifact tasks.named("sourceJar")
		}
	}
}

deployInator {
	modName = project.mod_name
	compatibleMinecraftVersions project.compatible_minecraft_versions
	modLoaders "neoforge"
	
	maven {
		publishTaskName = "publishMavenJavaPublicationToModmavenRepository"
	}
	
	curseforge {
		id = project.curseforge_project
		relations project.curseforge_project_relations
	}
	
	modrinth {
		id = project.modrinth_project
		relations project.modrinth_project_relations
	}
	
	discord {
		name = project.deploy_name
		iconUrl = project.deploy_discord_icon
		minecraftVersion = project.minecraft_version
	}
}